name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Set up JDK 11
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    # Install dependencies (e.g., node_modules for React Native)
    - name: Install dependencies
      run: |
        npm install  # or yarn install

    # Grant execute permission for gradlew (located in the android directory for React Native)
    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew

    # Build APK/AAB with Gradle (navigate to the android directory)
    - name: Build APK/AAB with Gradle
      run: |
        cd android  # Navigate to the android directory
        ./gradlew bundleRelease  # Generates AAB (Android App Bundle)

    # Install Fastlane
    - name: Install fastlane
      run: |
        gem install fastlane --user-install

    # Upload APK/AAB to Google Play
    - name: Upload to Google Play
      env:
        GOOGLE_PLAY_JSON_KEY: ${{ secrets.GOOGLE_PLAY_JSON_KEY }}  # Ensure secret is passed to Fastlane
      run: |
        # Store the Google Play JSON key in a temporary file
        echo "$GOOGLE_PLAY_JSON_KEY" > /tmp/google_play_key.json
        
        # Upload the AAB to the Google Play console using Fastlane
        fastlane supply --aab ./android/app/build/outputs/bundle/release/app-release.aab --json_key /tmp/google_play_key.json --package_name com.Bahrain_Harbour --track internal --release_status draft
